# Generated by Django 4.2.2 on 2023-06-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_nicho_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nicho_empresa',
            new_name='nicho_mercado',
        ),
    ]
