# Generated by Django 4.2.2 on 2023-06-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_vagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='caracteristica_empresa',
            field=models.TextField(),
        ),
    ]
