# Generated by Django 4.2.2 on 2023-09-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_empresa_usuario_vagas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='usuario',
        ),
    ]
