# Generated by Django 4.2.2 on 2023-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_alter_empresa_usuario_alter_vagas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_empresa'),
        ),
    ]
